### ISSUE TITLE
undefined method `state=' for nil:NilClass since 0.3.1

### ISSUE THREAD

**Issue by nvloff** [heroku/rack-timeout#92]
Yesterday we've upgraded rack-timeout to 0.3.1 from 0.2.4 and we started seeing this error on production (we're using heroku) :

```

    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/core.rb:168 :in `_set_state!`

    166     def self._set_state!(env, state)
    167       raise "Invalid state: #{state.inspect}" unless VALID_STATES.include? state
    168       env[ENV_INFO_KEY].state = state
    169       notify_state_change_observers(env)
    170     end

    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/core.rb:115 :in `block in call`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/core.rb:117 :in `call`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/core.rb:117 :in `block in call`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:39 :in `call`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:39 :in `run!`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:52 :in `run!`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:99 :in `block (2 levels) in run_loop!`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:99 :in `each`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:99 :in `block in run_loop!`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:80 :in `loop`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:80 :in `run_loop!`
    [GEM_ROOT]/gems/rack-timeout-0.3.1/lib/rack/timeout/support/scheduler.rb:72 :in `block (2 levels) in runner`
```

Rack middlewares on production:

```
use Honeybadger::Rack::UserInformer
use Honeybadger::Rack::UserFeedback
use Honeybadger::Rack::ErrorNotifier
use HireFire::Middleware
use Rack::Cors
use Rack::UTF8Sanitizer
use Rack::Sendfile
use ActionDispatch::Static
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f7d7d3117b0>
use Rack::Timeout
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use JQuery::FileUpload::Rails::Middleware
```

Tried reproducing locally but I can't seem to find the right conditions to do so.

**Comment by kch** [comment]
How frequently/consistently are you seeing this in production? Is it for all request? A particular set of? A seemingly random set?

Do you have the full logs for a failing request? I wanna see what rack-timeout logs before the failure.

Looking at the code in https://github.com/heroku/rack-timeout/blob/v0.3.2/lib/rack/timeout/core.rb you can see the value is init'd in L81, and `_set_state!` seems to get successfully called in L109… So I suspect something else during the request to be affecting `env` and for some reason clearing out rack-timeout's info struct. (and maybe more?)

`register_state_change` is called repeatedly in a separate thread, but I suspect the main thread would already be doing L125.

**Comment by nvloff** [comment]
> How frequently/consistently are you seeing this in production?

About 300 times for a 15h period.

> Is it for all requests?

Some. For other we do get standard RequestTimeout exceptions.

>  A particular set of? 

Seemingly random. But for endponts that don't usually (or at all) timeout 

> Do you have the full logs for a failing request? 

No, unfortunately. 

So the Rack::Timeout middleware order changed grabbed my attention from the change log. And we deployed a rendom fix that moved Rack::Timeout before Rack::Cors in the middleware list. And for the past 10h we haven't had a single error.

I'm closing this. I don't currently have logs or any more debug information, and we no longer see the issue.

**Comment by kch** [comment]
Yeah I was wondering if the middleware order was to blame. Can you paste here the new middleware list? Probably one of them is doing something funny.

**Comment by nvloff** [comment]
Ok, I spoke too soon :)

We encountered the same issue eventually. I insta-reverted to 0.2.4 once I saw it. 

It occurred exactly 2 times ~10min apart. 

So, I really want to be able to provide some more debug info, but I'm still unable to reproduce locally. And we can't run 0.3.x on production for now. Anything I can do to provide more info?

I'don't know what's the policy for issues like this, I reopened it, but I understand if due to the lack of debug data you close it.

**Comment by kch** [comment]
Well I'd like to get it fixed.

If I make a debug branch will you run it?

The idea, if the info struct is not present, is to give up on the timeout code but let the request finish normally, whilst along with it logging some debug info.

**Comment by nvloff** [comment]
Yep, sure we can run that.

**Comment by kch** [comment]
Ok, try with:

    gem "rack-timeout", github:"heroku", branch:"vanishing-env-info-debug"

This will log some extra stuff that'll be helpful in understanding what's going on. Additionally it'll not raise if info is not present.

It's a lot of logging per request so just run it long enough to run into the issue a few times. Maybe half a day or so?

You'll need a log retention add-on with heroku.

Can you open a ticket with heroku support and ask that it be sent my way? Also make sure you grant application access so I can inspect your log retention add-on.

**Comment by nvloff** [comment]
Hey, Thanks!

Just deployed to production and created the ticket with heroku. We've added papertrail for the logs hope the data size would be enough there.

**Comment by nvloff** [comment]
Ok, this started appearing now:

TypeError: nil is not a symbol

```
GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/logging-observer.rb:42 :in `log_state_change`
40     info = env[::Rack::Timeout::ENV_INFO_KEY]
41     level = STATE_LOG_LEVEL[info.state]
42     logger(env).send(level) do
43       s  = "source=rack-timeout"
44       s << " id="      << info.id           if info.id
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:199 :in `call`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:199 :in `block in notify_state_change_observers`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:199 :in `each`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:199 :in `notify_state_change_observers`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:176 :in `_set_state!`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:117 :in `block in call`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:119 :in `call`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/core.rb:119 :in `block in call`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:39 :in `call`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:39 :in `run!`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:52 :in `run!`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:99 :in `block (2 levels) in run_loop!`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:99 :in `each`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:99 :in `block in run_loop!`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:80 :in `loop`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:80 :in `run_loop!`
[GEM_ROOT]/bundler/gems/rack-timeout-60e99cb3108a/lib/rack/timeout/support/scheduler.rb:72 :in `block (2 levels) in runner`
```

**Comment by kch** [comment]
I made some updates to the branch and asked you on the heroku ticket to re-deploy but haven't heard from you since. Any news?

**Comment by nvloff** [comment]
Yeah, quite simple: we hit our papertrail plan limit and I was gonna deploy the branch tomorrow on next  month's quota. I'll reopen the ticket when it's done.

**Comment by metade** [comment]
We're seeing the same thing. Rolling back to an older version of `rack-timeout`.

We'll try running your branch on our staging environment to see if we can replicate the error.

**Comment by kch** [comment]
What I gather from the logs so far is, when this happens, `env` has been basically cleared. There's a single key in it. Next commit I'll print the key so we know which.

Also, all the failing calls happen coming from the `heartbeat_event` proc, which runs in another thread. Also, the heartbeat is basically irrelevant to the main operation of rack timeout. It's only really used for logging purposes atm. So it's fine to just bail if info is not present.

But I wanna get to the bottom of this first.

**Comment by kch** [comment]
Ok, about to push some updates. When you deploy with the new updates, can you set `Rack::Timeout::Logger.level  = Logger::DEBUG` or at least `Logger::INFO`?

**Comment by kch** [comment]
New things are in. Please run in prod a couple days, accumulate some logs, and let me know so I can download them. You might get attention faster if you notify me in the support ticket.

@metade if you wanna do the same, you're welcome. This branch is safe to run in prod, it should not explode as it just skips stuff if env has been cleared.

**Comment by nvloff** [comment]
I get the following error when I run this new debug branch, start the development server, and try to do a request.
```
=> Booting Thin
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23: [BUG] object allocation during garbage collection phase
ruby 2.0.0p481 (2014-05-08) [x86_64-darwin14.1.0]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:1613 p:---- s:12029 e:002028 CFUNC  :caller
c:1612 p:0018 s:12025 e:002020 METHOD /Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23
c:1611 p:0013 s:12015 e:002014 LAMBDA /Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:16 [FINISH]
c:1610 p:0021 s:12011 e:002005 METHOD /Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23
c:1609 p:0013 s:12000 e:001999 LAMBDA /Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:16 [FINISH]
c:1608 p:0021 s:11996 e:001990 METHOD /Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23
c:1607 p:0013 s:11985 e:001984 LAMBDA /Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:16 [FINISH]

... snip ..

/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23:in `__log_method_call'
/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:16:in `block (2 levels) in extended'
/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23:in `__log_method_call'
/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:16:in `block (2 levels) in extended'
/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23:in `__log_method_call'
/Users/nvloff/work/Textmaster.com/vendor/ruby/2.0.0/bundler/gems/rack-timeout-5e579ee5fe7b/lib/rack/timeout/core.rb:23:in `caller'

-- C level backtrace information -------------------------------------------

```

Full error: https://gist.github.com/nvloff/ccb7ebfecfe5f2d8dd80

**Comment by kch** [comment]
Ugh. Could you try with ruby 2.2.3?

**Comment by kch** [comment]
@metade which ruby version are you on btw?

**Comment by nvloff** [comment]
@kch not anytime soon. we'll be on 2.0 for a while. We have 2.2.3 under testing but we may decide against running it on prod. I'll know more next week.

**Comment by kch** [comment]
OK, I'll see if I can figure out wth is going on with 2.0.0

**Comment by kch** [comment]
Even for 2.0, there's a newer patchlevel ( 2.0.0-p647), you might want to at least look into that. Not sure if it would fix anything for this issue tho.

**Comment by kch** [comment]
@nvloff so I tried here with same ruby, rails, and thin versions, and the error did not happen for my test app.

**Comment by kch** [comment]
@nvloff you only tried that locally yes? I'd say try in new staging app on heroku? 

I also pushed a new commit to the branch. There's a slight chance it may make things better.

(Also if you recently updated OS X, any chance something's off with your ruby after that?)

**Comment by nvloff** [comment]
Hey, now I don't get that error, but just the dev server keeps on loading and never finishes a request. I now get this same behaviour even with the previous commit. 

It's probably something local, I'll check my setup and get back to you. May take me a couple of days as I'm a bit swamped with other things right now.

**Comment by ravi-ture** [comment]
Hi, we are getting the same error on our heroku deployed application. 

<pre>

NoMethodError: undefined method `state=' for nil:NilClass
…2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:  168:in `_​set_​state!'​
…2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:  115:in `block in call'​
…2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:  117:in `call'​
…2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:  117:in `block in call'​
…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   39:in `call'
​…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   39:in `run!'
​…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   52:in `run!'
​…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   99:in `block ​(2 levels)​ in run_​loop!'​…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   99:in `each'
​…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   99:in `block in run_​loop!'​
…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   80:in `loop'​
…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   80:in `run_​loop!'​
…ck-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:   72:in `block ​(2 levels)​ in runner'
</pre>

**Comment by nadavshatz** [comment]
I used to get this as well https://github.com/heroku/rack-timeout/issues/57 and never was able to resolve.
I subscribed to this issue and am really interested in its conclusion :)

**Comment by DSAMPAT** [comment]
@kch

I am using Heroku as well and have changed the logger to logger::ERROR and have set the rack_timeout.rb to the following:-

	Rack::Timeout::timeout = 120
	Rack::Timeout::Logger.logger = Logger.new($stderr)
	Rack::Timeout::Logger.level  = Logger::ERROR

The message still appears as below:-

	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.661861 #9] ERROR -- : listen loop error: undefined method `state=' for nil:NilClass (NoMethodError) 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.661942 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:168:in `_set_state!' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.661989 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:115:in `block in call' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662031 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:117:in `call' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662071 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:117:in `block in call' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662111 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:39:in `call' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662150 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:39:in `run!' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662190 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:52:in `run!' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662229 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99:in `block (2 levels) in run_loop!' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662269 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99:in `each' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662308 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99:in `block in run_loop!' 
	Dec 16 11:31:15 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662347 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:80:in `loop' 
	Dec 16 11:31:16 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662386 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:80:in `run_loop!' 
	Dec 16 11:31:16 xxxappname app/web.1:  E, [2015-12-16T03:31:15.662426 #9] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:72:in `block (2 levels) in runner' 

Please advise if there is anything else we can do to assist with more information to help resolve the issue.

**Comment by samandmoore** [comment]
migrating my comment over from the closed issue #57:

Seeing a similar issue on jruby 1.7.19 using puma 2.15.3 and rack-timeout 0.3.2.

```
NoMethodError: undefined method `state' for nil:NilClass
               log_state_change at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/logging-observer.rb:41
                           call at org/jruby/RubyProc.java:271
  notify_state_change_observers at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:192
                           each at org/jruby/RubyArray.java:1613
  notify_state_change_observers at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:192
                    _set_state! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:169
                           call at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:115
                           call at org/jruby/RubyProc.java:271
                           call at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:117
                           call at org/jruby/RubyProc.java:271
                           run! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:39
                           run! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:52
                      run_loop! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99
                           each at org/jruby/RubyArray.java:1613
                      run_loop! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:99
                           loop at org/jruby/RubyKernel.java:1507
                      run_loop! at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:80
                         runner at /code/jruby/1.9/gems/rack-timeout-0.3.2/lib/rack/timeout/support/scheduler.rb:72
```

It also appears to have resulted / coincided with a crash in the puma process. could be an out of memory issue?

**Comment by NielsKSchjoedt** [comment]
+1 We are seeing this too pretty frequently on our app deployed to dedicated servers (not on heroku). We are running 2.2.3

**Comment by DSAMPAT** [comment]
@kch Any update here?

**Comment by samandmoore** [comment]
I would like to add that I'm actually seeing these undefined method errors on 0.2.4 (which was believed not to have the issue) not just on the latest release. Interestingly, they're not crashing the process in 0.2.4, but they appear to be crashing the thread.

**Comment by kch** [comment]
Ok, I'm ready to get back to this.

So everyone willing to help, I still need data.

If you're willing, please run [this branch](https://github.com/heroku/rack-timeout/tree/vanishing-env-info-debug), and if you're on heroku, add a log retention add-on. (otherwise, you know, keep your logs somehow.)

It'll log A LOT OF DATA. I'm trying to track down what is resetting the env, so if it's nil I'll log stack traces for all methods sent to env during that request.

When you have some of those, please paste them here. All lines interesting to me start with `source=rack-timeout-debug`.

**Comment by kch** [comment]
Also keep in mind that this branch pretends everything is ok when our env info is nil and let's the request proceed as normal, just without enforcing timeout. Which is a nice benefit while we don't have a fix.

**Comment by DSAMPAT** [comment]
@kch Any chance you can make the branch into a rc release so we can test it and then revert if needed using the gemfile?

**Comment by kch** [comment]
@DSAMPAT why can't you just `gem "rack-timeout", github:"heroku", branch:"vanishing-env-info-debug"
`?

**Comment by kch** [comment]
Well, giving the wrong code wasn't very helpful. What I meant is, add this to your `Gemfile`:

```ruby
gem "rack-timeout", github:"heroku/rack-timeout", branch:"vanishing-env-info-debug"
```

I'm hoping to get this fixed for the next release, but I can only do that if I see some debug data as I have so far not been able to reproduce this nor observed it in any of our systems.

**Comment by DSAMPAT** [comment]
@kch used the above code and got the error immediately after updating the app. View updated error log below. Hope it is of use and related to the same issue.

```
Mar 08 20:36:12 appname heroku/web.1:  Starting process with command `bundle exec unicorn -p 8082 -c ./config/unicorn.rb` 
Mar 08 20:36:16 appname app/web.1:  I, [2016-03-09T04:36:16.251672 #3]  INFO -- : Refreshing Gem list 
Mar 08 20:36:19 appname app/web.1:  I, [2016-03-09T04:36:18.854026 #3]  INFO -- : listening on addr=0.0.0.0:8082 fd=9 
Mar 08 20:36:19 appname app/web.1:  I, [2016-03-09T04:36:18.893064 #6]  INFO -- : worker=0 ready 
Mar 08 20:36:19 appname app/web.1:  I, [2016-03-09T04:36:18.893274 #3]  INFO -- : master process ready 
Mar 08 20:36:19 appname app/web.1:  I, [2016-03-09T04:36:18.896350 #9]  INFO -- : worker=1 ready 
Mar 08 20:36:19 appname app/web.1:  I, [2016-03-09T04:36:18.898024 #12]  INFO -- : worker=2 ready 
Mar 08 20:36:19 appname heroku/web.1:  State changed from starting to up 
Mar 08 20:36:21 appname heroku/router:  at=info method=GET path="/" host=appname.herokuapp.com request_id=1e5218fc-12e5-4ea6-bb4f-c81678d169eb fwd="xxx.xxx.xxx.xxx" dyno=web.1 connect=2ms service=5ms status=500 bytes=38 
Mar 08 20:36:21 appname app/web.1:  source=rack-timeout id=1e5218fc-12e5-4ea6-bb4f-c81678d169eb wait=33172ms timeout=30000ms state=expired at=error 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559318 #12] ERROR -- : app error: Request older than 30000ms. (Rack::Timeout::RequestExpiryError) 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559404 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.3.2/lib/rack/timeout/core.rb:98:in `call' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559454 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559501 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559542 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559606 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559640 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559681 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559718 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559765 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559812 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559850 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559904 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load' 
Mar 08 20:36:21 appname app/web.1:  E, [2016-03-09T04:36:21.559971 #12] ERROR -- : /app/vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>' 
```

**Comment by mbasset** [comment]
:+1: We are also have this issue and have no idea whats causing it. It seems almost random even though we are sure its not.

**Comment by kch** [comment]
@DSAMPAT that seems just an artefact of having restarted the dyno. Some requests that had been waiting too long for the dyno to come back online will be deemed too old. Did the app run fine after that?

**Comment by kch** [comment]
@mbasset you're welcome to try this debug branch too then :)

**Comment by DSAMPAT** [comment]
@kch I have implemented the code change on the Production code but pushed it to a Staging site. Yes, the app is running fine with the code. Now whenever it resumes from an idle state, the same few lines come up, other than that, the old errors have not appeared.

Maybe @mbasset can confirm that his errors have disappeared as well.

**Comment by mbasset** [comment]
We tried the debug branch and got massive memory consumption. The application seemed to grow in memory size without bounds when using the debug branch. We have had to use a custom version of the gem where we essentially bypass the problem to avoid it translating into an end user 5xx error for now. Unfortunately not meaningful debug information could be retrieved when using the gem the first time as the server would go critical shortly after the code was used and become extremely unresponsive.

**Comment by mbasset** [comment]
Should mention we are using ruby 2.2.4 with rails 4.2.5.1 and a whole lot of other gems.

**Comment by kch** [comment]
@mbasset hum I do store a lot of stuff during the request in the debug branch, but it should all expire after that. I have an idea about how to do this without logging every damn access to env. I'll update the branch when I can. Hopefully soon.

**Comment by kch** [comment]
@DSAMPAT yeah the branch bypasses the error, but it logs a bunch of stuff when it happens. I'm looking for log lines containing `source=rack-timeout-debug`. Can you search your logs for some?

**Comment by kch** [comment]
@mbasset @DSAMPAT alright, I've updated the branch with new code. It should be a lot easier on your memory and logs. It'll only log the trace at the moment the rack-timeout key disappears from env.

We'll still be looking for log lines with `source=rack-timeout-debug`.

**Comment by DSAMPAT** [comment]
@kch Have you made the change on the actual release? The errors were occurring every 2 to 4 mins and stopped last night at around your last comment.

**Comment by kch** [comment]
I made the changes in the branch. If you bundle updated it'd update the branch.

**Comment by kch** [comment]
@DSAMPAT if you're seeing the errors then do you have the log lines that I need?

**Comment by DSAMPAT** [comment]
@kch The gem doesn't work after bundle update was done. It runs on my local machine, but does not work on Heroku. Can you do rc version? Then I can lock it in the gemfile to confirm that it is not any other gem causing the app to not compile. I think the Heroku bundler has an issue with using a branch.

No logs with source=rack-timeout-debug. Just the same old " #12] ERROR -- : listen loop error: undefined method `state=' for nil:NilClass (NoMethodError) "

**Comment by kch** [comment]
@DSAMPAT heroku has no issues with git branch gems. I even deployed a test app to confirm. What are you seeing that makes you believe that? Is it failing to deploy? Failing to start? Paste any relevant logs here.

**Comment by DSAMPAT** [comment]
@kch I have managed to deploy. Not sure what the issue was. Could have been another gem causing the bundle issue as I am using Windows mingw-32.

I am getting this notification below, should I change anything or is this fine?
` app/web.1:  `Rack::Timeout.timeout=`: class-level settings are deprecated. See README for examples on using the middleware initializer instead. `

**Comment by kch** [comment]
@DSAMPAT it's just a warning, doesn't really impact anything at the moment.

**Comment by beatjoerg** [comment]
We are seeing this issue also. I will try with your debug branch.

**Comment by beatjoerg** [comment]
Unfortunately we are on ruby 2.0... so the beta version is not going to work. Can you make a version of the 0.3.2?

**Comment by kch** [comment]
@beatjoerg it should work fine with 2.0. Any reason you think it wouldn't?

**Comment by beatjoerg** [comment]
@kch Because you use some methods in the code that are not available with ruby 2.0, like super_method. I tried to backport them, but I did not arrive to fix all in the timebox I had.
To see what I "fixed" so far: https://github.com/beatjoerg/rack-timeout/commits/26e05ee40322eae527aa3fd38a8d933e3dec1819/lib/rack/timeout/legacy.rb

**Comment by kch** [comment]
Oh `super_method` is really bad, it's 2.2 only. Ok, I'll get rid of that.

**Comment by kch** [comment]
@beatjoerg 0.4.2 is out with 2.0 compatibility. I also rebased the debug branch here so it should be good to go now. 

@samandmoore might work for you in jruby now too, give it a go.

**Comment by samandmoore** [comment]
@kch thanks. Still no luck for me running it because it's not ruby 1.9 compatible:

```
SyntaxError: /opt/rubies/jruby-1.7.24/lib/ruby/gems/shared/bundler/gems/rack-timeout-7a5914cc9734/lib/rack/timeout/core.rb:94: syntax error, unexpected tLABEL
    def initialize(app, service_timeout:nil, wait_timeout:nil, wait_overtime:nil, service_past_wait:false)
```

**Comment by kch** [comment]
@samandmoore ok so your jruby version also doesn't support named parameters. I'll see if I can make a version of the debug branch off 0.3.2…

**Comment by kch** [comment]
@samandmoore give it a go https://github.com/heroku/rack-timeout/tree/vanishing-env-info-debug-0.3.2

**Comment by samandmoore** [comment]
thanks, will give it a shot.

**Comment by kch** [comment]
Is anyone actually running this debug branch in a reasonably trafficked app? I'd've expected to have some useful log lines by now.

How about this: I'll mail some heroku swag to the first person who delivers log lines that enlighten me. Help us if you like purple stuff!

**Comment by samandmoore** [comment]
I'm working on it. Just in the midst of another big change. Will likely
have results for you tomorrow :)

**Comment by beatjoerg** [comment]
@kch Just deployed to production... Waiting for the errors...

**Comment by mbasset** [comment]
@kch Unfortunately last time we tried this branch we almost took down our production. We have created a bypass for the error but it still happens at quite a regular frequency. ~200 per hour.

**Comment by kch** [comment]
@mbasset I wonder if only injecting the hijack on a sample (like 10% or so) of the requests would make it more bearable for you. Lmk if it sounds like a good a idea and I'll add that as an option.

**Comment by mbasset** [comment]
@kch That sounds good in theory but even having it on 10% of our traffic could cause our servers to become unstable and die albeit more slowly. We may be able to try this in our staging environment as we recently created a script to simulate some production load. However need to find time to try this out.

**Comment by kch** [comment]
@mbasset well I'd make the frequency configurable. Also I believe I rewrote the debug code to be a lot nicer since you last tried it. Not sure.

**Comment by kch** [comment]
@mbasset so I did it. You can set the env var `RACK_TIMEOUT_HIJACK_FREQUENCY` to any number between `0` and `1.0` and that'll determine the frequency.

I've also made changes so I'm hijacking even less methods, trying to stay more out of the way.

**Comment by mbasset** [comment]
Cool I'll see when we get a chance to try this version out and see what happens.

**Comment by mbasset** [comment]
Just FYI still have not had a chance to look into this yet. Ideally if someone else has time.

**Comment by mbasset** [comment]
@kch Hoping to try out the branch next week. However I see it only sends warnings. In our production environment (which is the only environment this seems to happen in) how would you suggest getting the output. We are currently using an nginx/unicorn setup.

**Comment by samandmoore** [comment]
I've been working on updating the 0.3.2 branch to look like the newer one.
I tried to run it under a load test (because we only see these issues when
under reasonable load) and I haven't been able to reproduce it in
development mode. However, I was able to reproduce it in a capybara feature
spec. Unfortunately, that spec didn't have the logging in place. I am
hopefully going to try it in production in the next week or so.

**Comment by mbasset** [comment]
@kch We have been trying your latest branch out in an environment that normally causes ~100 of these errors an hour with rails 4.2.6 and it does not appear to be happening anymore. I wonder if the changes that were made to timing in that branch have solved the issue. Possibly also fixed with rails update. Will continue to monitor for the next while to see.

**Comment by beatjoerg** [comment]
@kch @mbasset : Same also here, we do not see the error anymore running the debug branch. (We use also rails 4.2.6.)

**Comment by samandmoore** [comment]
@kch I have a version of the debug branch in production, and i'm seeing occasional log statements like this:

```
[DM4PNP]2016-05-24 07:15:53 -0400 severity=WARN, source=rack-timeout-debug info-vanish id=4773927afb3ba69e09eed01d8ae1b6fd
```

Unfortunately, there are no other logs associated with that id value, so I've got no call stack for you. That makes me think that the method that is unsetting the env info is one of the methods we're not redefining with the logging behavior. Thoughts?

**Comment by nadavshatz** [comment]
I'm sorry for bumping this for everyone - did anyone have any success in resolving this?

**Comment by mbasset** [comment]
Rails 4.2.6 and the latest 0.4.2 version has fixed it entirely for us.

**Comment by nextofsearch** [comment]
Hi, I am suffering from the same issue with rack-timeout 0.3.2, ruby 1.9.3-p551 and Rails 3.2.22.5. Unfortunately I am stuck with what I have (can't upgrade ruby or Rails.). It seems that ruby 1.9.x works with 0.3.x so I can't use 0.4.x. I will try downgrade to 0.2.x and keep you posted.

**Comment by wuputah** [comment]
It _appears_ this has been resolved in some way or otherwise gone away, so closing pending new reports.

**Comment by katrinleinweber** [comment]
I saw essentially the same error in v0.5.1 (slightly different line numbers) and with Rails v6.0.3 and gitlab-puma v4.3.3.gitlab.2. 
It was preceded by 

```
/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/rack-timeout-0.5.1/lib/rack/timeout/support/scheduler.rb:73 run> terminated with exception (report_on_exception is true):
/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/rack-timeout-0.5.1/lib/rack/timeout/core.rb:168:in `_set_state!': undefined method `state=' for nil:NilClass (NoMethodError)
```

The only (remote) clue I have to hopefully help reproduce the issue, is that Unicode characters `Ç` & `Ã` are in a commit message, that's not being displayed where it should be. I'm grasping at straws here, but is string parsing involved at any point here?

**Comment by vermeeren** [comment]
Have been having this issue since upgrade to GitLab 13.3.2-ee (13.2.x did not happen). This is with 0.5.2, which I realise is not the latest version of this package. The two instances with EE Premium licence have this problem and a service restart "fixes" it until it occurs again. Another instance without a licence uploaded appears to not have this problem, but it could just be RNG. I will raise an issue with GitLab support regarding this.

```
#<Thread:0x000000012b38b6f8@/var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:73 run> terminated with exception (report_on_exception is true):
/var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/core.rb:168:in `_set_state!': undefined method `state=' for nil:NilClass (NoMethodError)
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/core.rb:113:in `block in call'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/core.rb:115:in `block in call'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:39:in `run!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:52:in `run!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:100:in `block (2 levels) in run_loop!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:100:in `each'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:100:in `block in run_loop!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:81:in `loop'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:81:in `run_loop!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:73:in `block (2 levels) in runner'
/var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/core.rb:168:in `_set_state!': undefined method `state=' for nil:NilClass (NoMethodError)
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/core.rb:113:in `block in call'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/core.rb:115:in `block in call'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:39:in `run!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:52:in `run!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:100:in `block (2 levels) in run_loop!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:100:in `each'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:100:in `block in run_loop!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:81:in `loop'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:81:in `run_loop!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-timeout-0.5.2/lib/rack/timeout/support/scheduler.rb:73:in `block (2 levels) in runner'
```

**Comment by vermeeren** [comment]
On another host the traceback is very different, so it is almost certain it is a problem in Puma or some component of GitLab and not this project, apologies for the noise. It also happened with GitLab 13.2.x fyi.

<details>

```
var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:837:in `block in with_new_connections_blocked': undefined method `clear' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:833:in `ensure in with_new_connections_blocked'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:850:in `with_new_connections_blocked'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `with_exclusively_acquired_all_connections'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:503:in `disconnect'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:525:in `disconnect!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1136:in `remove_connection'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1054:in `establish_connection'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:51:in `establish_connection'
        from /var/opt/gitlab/gitlab/config/initializers/active_record_lifecycle.rb:8:in `block (2 levels) in <top (required)>'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
        from /var/opt/gitlab/gitlab/config/initializers/active_record_lifecycle.rb:7:in `block in <top (required)>'
        from /var/opt/gitlab/gitlab/lib/gitlab/cluster/lifecycle_events.rb:147:in `each'
        from /var/opt/gitlab/gitlab/lib/gitlab/cluster/lifecycle_events.rb:147:in `call'
        from /var/opt/gitlab/gitlab/lib/gitlab/cluster/lifecycle_events.rb:114:in `do_worker_start'
        from /var/opt/gitlab/gitlab/config/puma.rb:57:in `block in _load_from'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:279:in `block in run_hooks'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:279:in `each'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:279:in `run_hooks'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:267:in `worker'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:138:in `block (2 levels) in spawn_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/nakayoshi_fork-0.0.4/lib/nakayoshi_fork.rb:23:in `fork'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/nakayoshi_fork-0.0.4/lib/nakayoshi_fork.rb:23:in `fork'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:138:in `block in spawn_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:134:in `times'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:134:in `spawn_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:204:in `check_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:487:in `run'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/launcher.rb:172:in `run'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cli.rb:80:in `run'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/bin/puma:10:in `<top (required)>'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
/var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:761:in `block in attempt_to_checkout_all_existing_connections': private method `select' called for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `attempt_to_checkout_all_existing_connections'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:753:in `block in with_exclusively_acquired_all_connections'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:829:in `with_new_connections_blocked'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `with_exclusively_acquired_all_connections'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:503:in `disconnect'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:525:in `disconnect!'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1136:in `remove_connection'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1054:in `establish_connection'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:51:in `establish_connection'
        from /var/opt/gitlab/gitlab/config/initializers/active_record_lifecycle.rb:8:in `block (2 levels) in <top (required)>'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
        from /var/opt/gitlab/gitlab/config/initializers/active_record_lifecycle.rb:7:in `block in <top (required)>'
        from /var/opt/gitlab/gitlab/lib/gitlab/cluster/lifecycle_events.rb:147:in `each'
        from /var/opt/gitlab/gitlab/lib/gitlab/cluster/lifecycle_events.rb:147:in `call'
        from /var/opt/gitlab/gitlab/lib/gitlab/cluster/lifecycle_events.rb:114:in `do_worker_start'
        from /var/opt/gitlab/gitlab/config/puma.rb:57:in `block in _load_from'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:279:in `block in run_hooks'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:279:in `each'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:279:in `run_hooks'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:267:in `worker'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:138:in `block (2 levels) in spawn_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/nakayoshi_fork-0.0.4/lib/nakayoshi_fork.rb:23:in `fork'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/nakayoshi_fork-0.0.4/lib/nakayoshi_fork.rb:23:in `fork'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:138:in `block in spawn_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:134:in `times'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:134:in `spawn_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:204:in `check_workers'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:487:in `run'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/launcher.rb:172:in `run'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cli.rb:80:in `run'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/bin/puma:10:in `<top (required)>'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
        from /var/opt/gitlab/gitlab/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
```

</details>
